// Copyright (c) 2020 Steve Jones
// SPDX-License-Identifier: BSD-2-Clause

package main

import (
	"strings"
	"testing"
)

const ExampleCredentials = `{
"instance_pub_key" : "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQVENDQWlXZ0F3SUJBZ0lJQWFXWWgydVRvOWN3RFFZSktvWklodmNOQVFFTkJRQXdRakVPTUF3R0ExVUUKQXhNRlpYVmhjbVV4RXpBUkJnTlZCQXNUQ2tWMVkyRnNlWEIwZFhNeERqQU1CZ05WQkFvVEJVTnNiM1ZrTVFzdwpDUVlEVlFRR0V3SlZVekFlRncweU1EQTBNREl4T0RNNU1URmFGdzB5TVRBME1ESXhPRE01TVRGYU1FY3hDekFKCkJnTlZCQVlUQWxWVE1RNHdEQVlEVlFRS0V3VkRiRzkxWkRFVE1CRUdBMVVFQ3hNS1JYVmpZV3g1Y0hSMWN6RVQKTUJFR0ExVUVBeE1LYVMwNE16RTJPREJtWkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU1RUDNQY09YekJMN2phbXJzaFZITTFOTngydVNGMjMyTXNpY0MxK05yVEZHRjB3RUxKTlZDemcrL3JNCjBWV0g0dm1WK1ZaOTAxRlBQaDhJSklkUzJOV0ZWRXg5U1E2cHlzZUZMOHNXT1g2RXMwTG40cW83VTJUWkJ6VXQKeFNSM3BJYlFKMks2MG1OSEU0SzloOGdJMThoRzZaMGZ0aXcxdVZkR3AwdkpSV0NaVjhWWDE0NTR4cnVZcU0vWQo0ODRFOUFDZGhiczVUM3pLTzlPKzV6K3NKMEkzaDJ0a21rUFFKZisweFdQY0NuazBjUVRHcGFxdFZCWkQ4R2Z2ClpVelVrQytjdkNKb0NSMzFxWHIzQ3lndFNSRHJTZkZidjF3bmZJL2hNQWI4V25CV2puZ3RsTmdmSWZBWGlUQkcKU1c0dHc0Z3g3S3ZZUHFEM1c0bHNJOExtK3dVQ0F3RUFBYU15TURBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVUwTlR0SDg5WVhxS3JOTzdoMTUyRDBXWW5uOUl3RFFZSktvWklodmNOQVFFTkJRQURnZ0VCCkFHYlZ0QTd5bVhPR0MyaHJ2dnAxNXBucTVWQzdOaGJHRjc0Q1FsQ1FhcEc0SzNTbEdkbGpkZWl2S2xWRTVvM2kKZkNxZGkzUTA2UHJpbksrSEhuaHFGWkVPV0g0SmhSKzhXeXJVQmV2V1FKdUpkOFhnR25nTUpwOGNWQzVoSEtGaQp4cmRqK2lkbjN6TTFPMWIwcVlJMU52U05Hb1NTbjJoblFzU1VQMU42Vy82MXplSFhWYnhHRjE4VWhacitlN0ZECnluRVp5R1dqRU9Fd0FUTDB3ZW9NRndIWW13MCtCTmlMNWxPVTdiV3dHTGFSUzg4OXNWamVkMys4UUdkY2N4aTkKRU9vWEEvSy9kc0FFSzE3RDJZN3B6aWRaSy94VktiNGRvMDBwVDd3R2tld1pscUxORGdQbjZwd3BQbWdNRWVWZQpFdUZSRHhvTTVGUXE0Q1dpRGszbDAxaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=                                                                                                                                                                                                                                                                                                                         ",
"iam_pub_key"      : "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lHQk9wdVBzTTdNQTBHQ1NxR1NJYjNEUUVCRFFVQU1FSXhDekFKQmdOVkJBWVQKQWxWVE1RNHdEQVlEVlFRS0V3VkRiRzkxWkRFVE1CRUdBMVVFQ3hNS1JYVmpZV3g1Y0hSMWN6RU9NQXdHQTFVRQpBeE1GWlhWaGNtVXdIaGNOTVRreE1qQTJNakF5TlRBeVdoY05NalF4TWpBMk1qQXlOVEF5V2pCQ01Rc3dDUVlEClZRUUdFd0pWVXpFT01Bd0dBMVVFQ2hNRlEyeHZkV1F4RXpBUkJnTlZCQXNUQ2tWMVkyRnNlWEIwZFhNeERqQU0KQmdOVkJBTVRCV1YxWVhKbE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBZ0hCYwo0cmlSMHpaODVrdUZBM1RaNnlINVNXN2pXWXpkc3UwWXhLUW9zRU5ZVmVzMnBvQ2RKZDdiL0MyTDlveVh4WXFwCm1yaUNla2d1ZFg2WWZHaWhNZGJNVGtld3dBSGxqZmh2d3h2cGpxdFdvS2dDakhMcm9ZbUdPUjZYNFVpV25GRngKMVRtRk1TdWxqRWlQMWRxN2dBRGluSWVFWFY1Z1Q3dUVvVHE0VVpRd1BrUWhEY2tkNjNtLzBwWWpzNjJaUVEvUQptRjE5SFFJM25NcjAvenhaYWtaY3pmckhEdDdLRFdZM3JlQmNTdWZTK2lETExNKzM2bWxjbzd5K3pOY0g4Wmd3CmlFcE9VS0MxendxbXhKSk8wMVJYTGk5Y0RuQ3Rycnc3S1ArT2VOSVFMbnorRmF5Z1dGRVF2TDB2NjBnVVJtNnMKZmxOa3hwODZSQmVWb1BZa3p3SURBUUFCb3pJd01EQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlFBY1JhKzhoekU3d0lwTHUxc3QxY3U1TjBSRnpBTkJna3Foa2lHOXcwQkFRMEZBQU9DQVFFQWVQYWg4UEFyCjVqcFp2eUhJQ05vSVVybW1uWGh1SXgzYkRQN3ZjMG52ZU01cHFIQTlDVk1SM1ZPcy9rbFVyTThrWVptRTdJaGMKRkVDNGo3V2NyVDBjTHNrcDZKY1FTUExVUkxVY0VLK1lscWxGR1ZsbDE2cHZldk5qQnd6aGlYU0tWRHBDclR0NwozU2Z3dlV2YzRodGwwb0RWRmowN254WXB1Z1Rwa0psWlIwSit6UnFEYTRMS0RNRVVNUnhsdHBCcGZqYTFoQU1DCkZCSVZzM1pGTmpKa2VBdnR4NG9jWndrcUhJM1VMSzlpRUg4a3FLS0tiNVJhN1MxcmZNZmExa0JYMnBucDI3WlMKVWVXU1p3T2RYVEcyUEJkazFrWjBwMFFqY3pFdFpIOW14ODRXdFlJTXdlV2FYR3A3TGVNVnB0am1FYXFhN3ZDZgp4RGo4WGduUS8rZVNYQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K                                                                                                                                                                                                                                                                                                                                         ",
"iam_token"        : "NULLCEUCALYPTUSAUTHSIGNATPLACEHOLDER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
"euca_pub_key"     : "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lHQk9PeWZyL2hNQTBHQ1NxR1NJYjNEUUVCRFFVQU1FY3hDekFKQmdOVkJBWVQKQWxWVE1RNHdEQVlEVlFRS0V3VkRiRzkxWkRFVE1CRUdBMVVFQ3hNS1JYVmpZV3g1Y0hSMWN6RVRNQkVHQTFVRQpBeE1LWlhWallXeDVjSFIxY3pBZUZ3MHhPVEV5TURZeU1ESTFNREZhRncweU5ERXlNRFl5TURJMU1ERmFNRWN4CkN6QUpCZ05WQkFZVEFsVlRNUTR3REFZRFZRUUtFd1ZEYkc5MVpERVRNQkVHQTFVRUN4TUtSWFZqWVd4NWNIUjEKY3pFVE1CRUdBMVVFQXhNS1pYVmpZV3g1Y0hSMWN6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFJRDN6em14cllsaThFWDhuUmZORmVtMzFONG1pbWM2bzB6cVM2aXdWSnQwRDZYSkplckU2d2U4CksrWU1TcU9TM0lVeEVGeUtMRUNMenR2ekJMbk4wRXc0WGRjSkt6L1R3WVpLU25WKytYaUozWnJoMGFjUzJNeW4KMTV6dWJ5c0xKR1U5Z1NMeDdGbEhiZlZiMjVoSjBUNG42ajFjMGtRMUVsSWEvZGpiMGpCMExQV0ZwUCttOG1HOAp0S3dxdnFVSE1LQ1ozWTdjdlJucHZvMFZ4djhoSGJ4NjZqaGRQcmUvUFhYWHR1UURrZlpuV0lETUVFekpEZkJjCmM1b1lRcStwMUZpT0dIdXhWSjNrK3JiZ2ZsMU4yNDZBK3B2QUhVb0xKT2p1OWZtc29GVWRWcytuQXpaU244My8KdXYxbktWck9kZUhJMEtIM0p5bnJNY2gvbi8yS3M4RUNBd0VBQWFNeU1EQXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVZzhDaXZKcXhVazVJTE5xellxRng0VzJ5K0ljd0RRWUpLb1pJaHZjTkFRRU5CUUFECmdnRUJBSGtaMGYzVTR1MTNlRWdwN0wwZEZhSWxzSzNXWjZiWDlmY2tKQU1QQ2ZOa1pCN3hEWXZES24yTDhnTjIKL2Z4anZ0NytaMDI0NGx0NGpYREJOM0p5dUhiU3oxSC9ob3MrL3FMTUl6TmlienBlZS8zRnFqeGJrNEFhV0NxNQplZ29SdnUvYW5IQzB2dVdVQTcxanIxQ0NlVTJNa1pRT04wbGR3SXhIcHNiNGdMcGZiVER6bXlVUjVJeURzNzV4CnlFamFMUHlmQlUwK3RrZG1iY3NDVjVueUw0VUkwZlM5Mnc3alVBZzY2K3UwejdLR0RMMzNyM0gySmUzYWhlMDIKL2tEU01EMU9yWTJkbzZrbzUzT3pqK2dibXp2RVd0ZGV5ZjBjYXFlWmd1TzVsZUNsZUc4QlRodnQzb1R0Ty9SRApvWEVoVEhjeEZwUU9ZRVNkcVpMUHd4dWhhODA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ",
"instance_pk"      : "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeEEvYzl3NWZNRXZ1TnFhdXlGVWN6VTAzSGE1SVhiZll5eUp3TFg0MnRNVVlYVEFRCnNrMVVMT0Q3K3N6UlZZZmkrWlg1Vm4zVFVVOCtId2draDFMWTFZVlVUSDFKRHFuS3g0VXZ5eFk1Zm9TelF1ZmkKcWp0VFpOa0hOUzNGSkhla2h0QW5ZcnJTWTBjVGdyMkh5QWpYeUVicG5SKzJMRFc1VjBhblM4bEZZSmxYeFZmWApqbmpHdTVpb3o5amp6Z1QwQUoyRnV6bFBmTW83MDc3blA2d25RamVIYTJTYVE5QWwvN1RGWTl3S2VUUnhCTWFsCnFxMVVGa1B3Wis5bFROU1FMNXk4SW1nSkhmV3BldmNMS0MxSkVPdEo4VnUvWENkOGorRXdCdnhhY0ZhT2VDMlUKMkI4aDhCZUpNRVpKYmkzRGlESHNxOWcrb1BkYmlXd2p3dWI3QlFJREFRQUJBb0lCQVFDeG55RnpYVHpWZDJUSApkRGlTVzdGdE9VLytmcjhtMElFQ2Z4K2J4MlZ1WGNVVjM0Nnd5aWZCUk01ang1eTZYUkkvUlNTUHZBeHU5RmgyCktwMVZUN1FMdE8vTElCSEl6QUJldzRXcCttZDUvR1NlNzQ5RTQ5eElWK29Vdm5PRTl6TkJ3MkI3TEgrZjIydU0KbllKZXNjd3pzRExDMjFEaU9vVy8wTTJOZGpsNUtidm5TLzJhNFlTRnFRRGhrQkY1aUZUSXBSVnpiQ1Y4WXB2MgpYZ2ljQzNhVWlvNXJ5OUc4alFIenpxSW1IR2FKdy9VMnhHNWJreGZHRDlMWnRVcmlrdms4RTJkbDNHSU5BUE9hCmVjNmxncmI4ZnM0bTBkb01CaVdPcXhreHVrUGhwTS9RbU4wbUlLaVlabkhkZWJsWldnT2RzSzBTb1BHb1htb2sKUHlrL1p5RzlBb0dCQVBHaExaYllmN1M2Z0g1ZG41U2IxTlZJaWU0Znk1ZlBmRE15R2oydzVYQ1pHL0M2MWRtVApzNUdzbFNET0pJTFBxZlpLUnNyM0RHWHhTY2lYYXpZM1duaWl2bVJUZm9vTkxBU2I2cEZITjYwN2JQNUhMMjdCCmdBUGNZS09hQVdOUi9qUmo2KzJuRFhPTnREeXRZN1ZtZENJSlZXYVR2blREUklMbmd0amUvSGpqQW9HQkFNKzQKNm1udmowNXFRbWZLZkM0Q3ExYk9XZm4wbEZ3TDFhdWh4dUowYyt6NzVZZEUrWW55OGNpS1hPWlcrR2ZZYUVERwptN2h1bStKUCtiVWR0V0hvSVpHZGJuRnVndkpaeldvRy85aTFuY3hld1BCb29XMFowSkYra0hTQUxhK1EzSTA2Ck0zWEIvdDJ6Y0lOZW8xK1phcTNTOUw1b2c2cC9Nc0JXWFVFVlA4ajNBb0dCQUp3d1hxTENZWkoyZC9hM0dCOWMKdDdBQ2lyNDFLVXFCWVR4S3A3RzI5aWpabjdqMVhLU2ZHQlVUSlBhbXFlMHd4U0dpRTY3QkVPK1lqK1F0RksxZwpESWdzVXJ2UlNOdDk5alVvZi9EV3cwT2tSU2o4NU1sSUpUTFpzbEl1aTdVaTNCb0xlUWNPMCtBYytpTzZ4TmdPCldRVmpXU1BNWHZGbEE1VkdoMHNlb0w2WEFvR0FUWEhSNCtFdStydGZPcmNoaVQzeGg1R3p0aDliMk4ySXNrN0UKaWRXRkN3djNUWEdIMzhpMklHQ0Z0bE1pbGdUM0NYK0N1MFp4MC9TaFVzZGF3ci83RkFFd0ZoWnZ0OCtIYUVwbgp4UEloZlBxdTBITVNERTBkbDhFcU5tVTdvME5ORjFKbHNUZTh3QWVRb1VuOWV6MEZxdjBGeHAvTXh4cFpYNkJUCmNGcHR4NDBDZjAvYWREVXhqZXlENGczUFlaZXpISTVDcTkwRzBLMlBRZnVxYUNHYVQzTDIxNVdXNFBra1E4WnMKWitYSG5DallkdEloRnJZY0JnY2RiUEJoZHZMY1VJZTVZcTN2ekxlbzQyZWZkZi9WZmhDY0N1UU9MeUh1ZmZZRgpDMFo0QVdzSWE5TGRWeEQ4ZEhycHFvS2ZSRjRobzlKM0ZoalpYUzErRXNIZ0tuMk5QSHc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==                                                                                                                                                                      "
}`

// Test credential JSON parse and cleanup
func TestCredentialsRead(t *testing.T) {
	credentials, err := CredentialString(ExampleCredentials)
	if err != nil {
		t.Errorf("CredentialString(ExampleCredentials) = _, error; %s", err.Error())
	}
	credentialFields := map[string]string{
		"InstancePublicKey":   credentials.InstancePublicKey,
		"InstancePrivateKey":  credentials.InstancePrivateKey,
		"IamPublicKey":        credentials.IamPublicKey,
		"IamToken":            credentials.IamToken,
		"EucalyptusPublicKey": credentials.EucalyptusPublicKey,
	}
	for name, value := range credentialFields {
		if value == "" {
			t.Errorf("CredentialString(ExampleCredentials).%s is empty", name)
		}
		if strings.HasSuffix(value, " ") {
			t.Errorf("CredentialString(ExampleCredentials).%s not trimmed", name)
		}
	}
}
